export const IS_HIDE_NOTIFICATION = 'admin/IS_HIDE_NOTIFICATION'
//READ
export const IS_LOAD_PRODUCTS = 'admin/IS_LOAD_PRODUCTS'
export const FETCH_PRODUCTS_SUCCESS = 'admin/FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_ERROR = 'admin/FETCH_PRODUCTS_ERROR'
export const FETCH_ONE_PRODUCTS_SUCCESS = 'admin/FETCH_ONE_PRODUCTS_SUCCESS'
export const FETCH_ONE_PRODUCTS_ERROR = 'admin/FETCH_ONE_PRODUCTS_ERROR'
//CREATE
export const IS_CREATE_PRODUCT = 'admin/IS_CREATE_PRODUCT'
export const CREATED_PRODUCT_SUCCESS = 'admin/CREATED_PRODUCT_SUCCESS'
export const CREATED_PRODUCT_ERROR = 'admin/CREATED_PRODUCT_ERROR'
//UPDATE
export const IS_UPDATING_PRODUCT = 'admin/IS_UPDATING_PRODUCT'
export const UPDATED_PRODUCTS_SUCCESS = 'admin/UPDATED_PRODUCTS_SUCCESS'
export const UPDATED_PRODUCTS_ERROR = 'admin/UPDATED_PRODUCTS_ERROR'
//DELETE
export const DELETE_PRODUCT_SUCCESS = 'admin/DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'admin/DELETE_PRODUCT_ERROR'
export const IS_HIDE_PRODUCT = 'admin/IS_HIDE_PRODUCT'