//GET ALL
export const IS_USERS_FETCHING = 'admin/IS_USERS_FETCHING'
export const GET_USERS_SUCCESS = 'admin/GET_USERS_SUCCESS'
export const GET_USERS_ERROR = 'admin/GET_USERS_ERROR'
//GET ONE
export const IS_USER_FETCHING = 'admin/IS_USER_FETCHING'
export const GET_USER_SUCCESS = 'admin/GET_USER_SUCCESS'
export const GET_USER_ERROR = 'admin/GET_USER_ERROR'
//CREATE
export const IS_CREATING_USER = 'admin/IS_CREATING_USER'
export const IS_HIDE_AFTER_CREATE = 'admin/IS_HIDE_AFTER_CREATE'
export const USER_CREATED_SUCCESS = 'admin/USER_CREATED_SUCCESS'
export const USER_CREATED_ERROR = 'admin/USER_CREATED_ERROR'
//UPDATE
export const IS_UPDATING_USER = 'admin/IS_UPDATING_USER'
export const UPDATED_USER_SUCCESS = 'admin/UPDATED_USER_SUCCESS'
export const UPDATED_USER_ERROR = 'admin/UPDATED_USER_ERROR'
//DELETE
export const DELETE_USER_SUCCESS = 'admin/DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'admin/DELETE_USER_ERROR'
export const IS_HIDE_USER = 'admin/IS_HIDE_USER'
export const IS_HIDE_NOTIFICATION = 'admin/IS_HIDE_NOTIFICATION'