//CREATE
export const DOWNLOAD = 'admin/DOWNLOAD'
export const CREATED_CATEGORY_SUCCESS = 'admin/CREATED_CATEGORY_SUCCESS'
export const CREATED_CATEGORY_ERROR = 'admin/CREATED_CATEGORY_ERROR'
export const IS_HIDE_NOTIFICATION = 'admin/IS_HIDE_NOTIFICATION'
//VIEW
export const IS_DOWNLOAD_CATEGORY = 'admin/IS_DOWNLOAD_CATEGORY'
export const VIEW_CATEGORY_SUCCESS = 'admin/VIEW_CATEGORY_SUCCESS'
export const VIEW_CATEGORY_ERROR = 'admin/VIEW_CATEGORY_ERROR'
//UPDATE
export const IS_UPDATING_CATEGORY = 'admin/IS_UPDATING_CATEGORY'
export const UPDATED_CATEGORY_SUCCESS = 'admin/UPDATED_CATEGORY_SUCCESS'
export const UPDATED_CATEGORY_ERROR = 'admin/UPDATED_CATEGORY_ERROR'
//DELETE
export const DELETE_CATEGORY_SUCCESS = 'admin/DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_ERROR = 'admin/DELETE_CATEGORY_ERROR'
export const IS_HIDE_CATEGORY = 'admin/IS_HIDE_CATEGORY'
