export const IS_CHECKING_OUT = 'checkout/IS_CHECKING_OUT'
export const CONFIRM_CHECKOUT_SUCCESS = 'checkout/CONFIRM_CHECKOUT_SUCCESS'
export const CONFIRM_CHECKOUT_ERROR = 'checkout/CONFIRM_CHECKOUT_ERROR'
