export const LOAD_PROFILE_SUCCESS = 'profile/LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'profile/LOAD_PROFILE_ERROR';
export const IS_UPDATING_USER_PROFILE = 'profile/IS_UPDATING_USER_PROFILE'
export const UPDATED_USER_PROFILE_SUCCESS = 'profile/UPDATED_USER_PROFILE_SUCCESS'
export const UPDATED_USER_PROFILE_ERROR = 'profile/UPDATED_USER_PROFILE_ERROR'