export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';
export const IS_UPDATING_USER_PROFILE = 'IS_UPDATING_USER_PROFILE'
export const UPDATED_USER_PROFILE_SUCCESS = 'UPDATED_USER_PROFILE_SUCCESS'
export const UPDATED_USER_PROFILE_ERROR = 'UPDATED_USER_PROFILE_ERROR'